name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.7.0

      - name: Set up Git repository
        uses: actions/checkout@v4

      - run: sudo apt-get update
      - run: make depext-deb

      - name: build VKR
        run: make vkr.pdf

      - name: build talk
        run: make talk.pdf

      - name: Upload PDF VKR file
        uses: actions/upload-artifact@v4
        with:
          name: VKR
          path: vkr.pdf

      - name: Upload PDF talk file
        uses: actions/upload-artifact@v4
        with:
          name: talk
          path: talk.pdf
